const gridInitData = [
  {
    pattern: "MyFirstPattern",
    options: {
      tempo: 120,
      swing: 0,
      mainvol: 80,
    },
    grid: [
      {
        name: "kick",
        sound: "C1",
        vol: 1,
        muted: 0,
        steps: [
          { time: "0:0:0", active: false, id: null },
          { time: "0:0:1", active: false, id: null },
          { time: "0:0:2", active: false, id: null },
          { time: "0:0:3", active: false, id: null },
          { time: "0:1:0", active: false, id: null },
          { time: "0:1:1", active: false, id: null },
          { time: "0:1:2", active: false, id: null },
          { time: "0:1:3", active: false, id: null },
          { time: "0:2:0", active: false, id: null },
          { time: "0:2:1", active: false, id: null },
          { time: "0:2:2", active: false, id: null },
          { time: "0:2:3", active: false, id: null },
          { time: "0:3:0", active: false, id: null },
          { time: "0:3:1", active: false, id: null },
          { time: "0:3:2", active: false, id: null },
          { time: "0:3:3", active: false, id: null },
        ],
      },
      {
        name: "clap",
        sound: "D1",
        vol: 1,
        muted: 0,
        steps: [
          { time: "0:0:0", active: false, id: null },
          { time: "0:0:1", active: false, id: null },
          { time: "0:0:2", active: false, id: null },
          { time: "0:0:3", active: false, id: null },
          { time: "0:1:0", active: false, id: null },
          { time: "0:1:1", active: false, id: null },
          { time: "0:1:2", active: false, id: null },
          { time: "0:1:3", active: false, id: null },
          { time: "0:2:0", active: false, id: null },
          { time: "0:2:1", active: false, id: null },
          { time: "0:2:2", active: false, id: null },
          { time: "0:2:3", active: false, id: null },
          { time: "0:3:0", active: false, id: null },
          { time: "0:3:1", active: false, id: null },
          { time: "0:3:2", active: false, id: null },
          { time: "0:3:3", active: false, id: null },
        ],
      },
      {
        name: "closed hihat",
        sound: "E1",
        vol: 1,
        muted: 0,
        steps: [
          { time: "0:0:0", active: false, id: null },
          { time: "0:0:1", active: false, id: null },
          { time: "0:0:2", active: false, id: null },
          { time: "0:0:3", active: false, id: null },
          { time: "0:1:0", active: false, id: null },
          { time: "0:1:1", active: false, id: null },
          { time: "0:1:2", active: false, id: null },
          { time: "0:1:3", active: false, id: null },
          { time: "0:2:0", active: false, id: null },
          { time: "0:2:1", active: false, id: null },
          { time: "0:2:2", active: false, id: null },
          { time: "0:2:3", active: false, id: null },
          { time: "0:3:0", active: false, id: null },
          { time: "0:3:1", active: false, id: null },
          { time: "0:3:2", active: false, id: null },
          { time: "0:3:3", active: false, id: null },
        ],
      },
      {
        name: "open hihat",
        sound: "F1",
        vol: 1,
        muted: 0,
        steps: [
          { time: "0:0:0", active: false, id: null },
          { time: "0:0:1", active: false, id: null },
          { time: "0:0:2", active: false, id: null },
          { time: "0:0:3", active: false, id: null },
          { time: "0:1:0", active: false, id: null },
          { time: "0:1:1", active: false, id: null },
          { time: "0:1:2", active: false, id: null },
          { time: "0:1:3", active: false, id: null },
          { time: "0:2:0", active: false, id: null },
          { time: "0:2:1", active: false, id: null },
          { time: "0:2:2", active: false, id: null },
          { time: "0:2:3", active: false, id: null },
          { time: "0:3:0", active: false, id: null },
          { time: "0:3:1", active: false, id: null },
          { time: "0:3:2", active: false, id: null },
          { time: "0:3:3", active: false, id: null },
        ],
      },
    ],
  },
];

export { gridInitData };